#############################################################################
# Makefile for building: XShows
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  XShows.pro
# Template: subdirs
# Command: E:\Qt\Qt5.5.0\5.5\mingw492_32\bin\qmake.exe -spec win32-g++ "CONFIG+=debug" -o Makefile XShows.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = E:\Qt\Qt5.5.0\5.5\mingw492_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src \
		sub-bin \
		sub-3rdparty


sub-src-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile
	cd src\ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-bin-qmake_all:  FORCE
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile
	cd bin\ && $(MAKE) -f Makefile qmake_all
sub-bin: FORCE
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-bin-make_first: FORCE
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-bin-all: FORCE
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-bin-clean: FORCE
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-bin-distclean: FORCE
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-bin-install_subtargets: FORCE
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-bin-uninstall_subtargets: FORCE
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-3rdparty-qmake_all:  FORCE
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile
	cd 3rdparty\ && $(MAKE) -f Makefile qmake_all
sub-3rdparty: FORCE
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile
sub-3rdparty-make_first: FORCE
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-3rdparty-all: FORCE
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-3rdparty-clean: FORCE
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-3rdparty-distclean: FORCE
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-3rdparty-install_subtargets: FORCE
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-3rdparty-uninstall_subtargets: FORCE
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: XShows.pro ../../Qt5.5.0/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf ../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/spec_pre.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/qdevice.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/device_config.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/qconfig.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_functions.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_config.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/qt_config.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/spec_post.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/exclusive_builds.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/default_pre.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/default_pre.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/resolve_config.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/exclusive_builds_post.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/default_post.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/rtti.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/precompile_header.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/warn_on.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/windows.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/testcase_targets.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/exceptions.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/yacc.prf \
		../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/lex.prf \
		XShows.pro
	$(QMAKE) -spec win32-g++ "CONFIG+=debug" -o Makefile XShows.pro
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/spec_pre.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/qdevice.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/device_config.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/qconfig.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_core.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_help.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_location.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_network.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_script.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_functions.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_config.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/qt_config.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/spec_post.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/exclusive_builds.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/default_pre.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/default_pre.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/resolve_config.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/exclusive_builds_post.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/default_post.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/rtti.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/precompile_header.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/warn_on.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/windows.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/testcase_targets.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/exceptions.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/yacc.prf:
../../Qt5.5.0/5.5/mingw492_32/mkspecs/features/lex.prf:
XShows.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ "CONFIG+=debug" -o Makefile XShows.pro

qmake_all: sub-src-qmake_all sub-bin-qmake_all sub-3rdparty-qmake_all FORCE

make_first: sub-src-make_first sub-bin-make_first sub-3rdparty-make_first  FORCE
all: sub-src-all sub-bin-all sub-3rdparty-all  FORCE
clean: sub-src-clean sub-bin-clean sub-3rdparty-clean  FORCE
distclean: sub-src-distclean sub-bin-distclean sub-3rdparty-distclean  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets sub-bin-install_subtargets sub-3rdparty-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets sub-bin-uninstall_subtargets sub-3rdparty-uninstall_subtargets FORCE

sub-src-debug:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-bin-debug:
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-3rdparty-debug:
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-src-debug sub-bin-debug sub-3rdparty-debug

sub-src-release:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-bin-release:
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-3rdparty-release:
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile release
release: sub-src-release sub-bin-release sub-3rdparty-release

sub-src-check:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\src\src.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-bin-check:
	@if not exist bin\ mkdir bin\ & if not exist bin\ exit 1
	cd bin\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\bin\bin.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-3rdparty-check:
	@if not exist 3rdparty\ mkdir 3rdparty\ & if not exist 3rdparty\ exit 1
	cd 3rdparty\ && ( if not exist Makefile $(QMAKE) E:\Qt\Project\XShows\3rdparty\3rdparty.pro -spec win32-g++ "CONFIG+=debug" -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-check sub-bin-check sub-3rdparty-check
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

