#ifndef XFRAMEPLUGIN_GLOBAL_H
#define XFRAMEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XFRAMEPLUGIN_LIBRARY)
#  define XFRAMEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XFRAMEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#define XFRAME_VER_MAJOR 1
#define XFRAME_VER_MINOR 0
#endif // XFRAMEPLUGIN_GLOBAL_H
